version: '3'

services:
  pgsql:
    platform: "linux/amd64"
    image: postgres:10
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      # POSTGRES_INITDB_ARGS:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  app:
    platform: "linux/amd64"
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_NAME: test_db
      DATABASE_HOST: pgsql
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_SCHEMA: public
      PUBLIC_URL: https://localhost:1337
    volumes:
      - ./src:/app/src
      # - /node_modules
    ports:
      - '1337:1337'
    links:
      - pgsql:pgsql
    depends_on:
      - pgsql
    command: npm run develop
volumes:
  db:
    driver: local
